### ISSUE TITLE
Investigate CLI issues for fresh installations

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native#221]
There's currently some headaches involved in first getting the CLI bundle server to work correctly on Windows.  We need to nail down the issue (whether it's a particular version of node, an admin privileges requirement, etc.).

**Comment by rozele** [comment]
Copy-paste email from @ebragge:

When I started cli.js from command prompt this function always returned false, because root started with ‘C:’ and child started with ‘c:’:
 
\react-native\node_modules\node-haste\lib\fastfs.js
 
function isDescendant(root, child) {
  return child.startsWith(root);
}

My current fix:
 
\react-native\local-cli\default.config.js
 
function getRoots() {
  if (__dirname.match(/node_modules[\/\\]react-native[\/\\]local-cli$/)) {
    // Packager is running from node_modules.
    // This is the default case for all projects created using 'react-native init'.
    return [path.resolve(__dirname, '../../..')];
  } else if (__dirname.match(/Pods[\/\\]React[\/\\]packager$/)) {
     // React Native was installed using CocoaPods.
    return [path.resolve(__dirname, '../../..')];
  } else {
    return [path.resolve(__dirname, '..')];
  }
}
 
function getRoots() {
  var dir = __dirname.replace(__dirname.substr(0,1),__dirname.substr(0,1).toLowerCase());
  
  if (dir.match(/node_modules[\/\\]react-native[\/\\]local-cli$/)) {
    // Packager is running from node_modules.
    // This is the default case for all projects created using 'react-native init'.
    return [path.resolve(dir, '../../..')];
  } else if (dir.match(/Pods[\/\\]React[\/\\]packager$/)) {
     // React Native was installed using CocoaPods.
    return [path.resolve(dir, '../../..')];
  } else {
    return [path.resolve(dir, '..')];
  }
}

**Comment by mpodwysocki** [comment]
Fixed as per https://github.com/ReactWindows/react-native/commit/7440f6ca917afb1c9bf2c064e41e8c1d3e002f6a
