### ISSUE TITLE
Out of interest - why C# and not C++?

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native#344]
Great news that this project has been created. My only question is the language and runtime used. I would have expected the native part of the library to be written in C++, avoiding the use of two Garbage Collectors.

**Comment by mpodwysocki** [comment]
@joewood first, thank you for the kind words on our progress. 

Obviously we want performance as one of the key characteristics of the UWP support for React-Native, in addition of course of developer ergonomics.  We have done some exhaustive work internally to make what we do as performance oriented as possible, especially with compiling to [.NET Native](https://msdn.microsoft.com/en-us/library/dn584397(v=vs.110).aspx).  We believe for now, that C# gives us the right level of performance and developer experience given those options.
