### ISSUE TITLE
Unable to run Playground project--Node packager fails to resolve UIExplorerApp.windows.js.

### ISSUE THREAD

**Issue by pingzing** [ReactWindows/react-native#347]
When attempting to load the Javascript bundle in the Playground project, the node server returns a 404 with the following message:

{"message":"Cannot find entry file Examples/UIExplorer/UIExplorerApp.windows.js in any of the roots: [\"D:\\\\node-test\\\\react-native\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}

I've modified `node-haste`'s `extractRequires.js` as noted in the readme, and am not sure why the packager can't resolve the file.

**Comment by joewood** [comment]
I'm seeing this same error too. I've tried to two different machines with the same error, even after the modification to **extractRequires.js**.

**Comment by Pokute** [comment]
Had the same problem and tried to bundle packages from the command line. In the end, I tried multiple variations with entry files in different locations which all failed with the same error.

**Comment by rozele** [comment]
Okay, I think we've seen this one before, just haven't resolved it in the ReactWindows branch.  Can you guys take a look at https://github.com/ReactWindows/react-native/issues/221
and see if this solves the issue?

**Comment by joewood** [comment]
Yes, that solved it. 
That's strange. I suggested the changes to the original project to enable Windows packager support (serving the package to an iOS device) - https://github.com/facebook/react-native/issues/468 - over a year ago!  I didn't have the issue with drive case sensitivity back then. Plus, surely this would impact Android react-native development?

Delving into this a bit more, I notice that these two functions return different results and don't normalize the case of the drive-level.
```javascript
path.resolve("c:\code"); // ->> returns c:\code
path.resolve("C:\code"); // ->> returns C:\code
```
There seems to be multiple tickets on this, so not surprised the behavior appears to have changed in node.js (mainly with issues relating to the module cache). 

This line in **path.js** indicates that `resolve` converts to lowercase: [nodejs/node-v0.x-archive/lib/path.js#L109](https://github.com/nodejs/node-v0.x-archive/blob/a05f973f82d2be8527aad4c371d40d3c7e4c564e/lib/path.js#L109)

Although that seems to have changed in the current version:[nodejs/node//lib/path.js#L177](
https://github.com/nodejs/node/blob/7c9a691ee7d13ccf1c883e27fdb96eccc8b73d5e/lib/path.js#L177)

**Comment by mpodwysocki** [comment]
Closing as per fix in the `WindowsStore` branch commit: https://github.com/ReactWindows/react-native/commit/7440f6ca917afb1c9bf2c064e41e8c1d3e002f6a
