### ISSUE TITLE
Add Vibration Module

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native#349]
Needs both native module and Windows-specific JavaScript module.

**Comment by christopherdro** [comment]
I can try and take this on as my first Windows module if you'd like.  I just got my surface book today :) Just waiting for the phone now.

**Comment by mpodwysocki** [comment]
@christopherdro I already have it done and just need to send in a PR. Much appreciated for your willingness to help.  Try picking a module from the help wanted tags to see which ones you can help us with.  Thanks!
