### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by Kennytian** [ReactWindows/react-native#365]
Hello,

Now show red box dialog error message:  Unable to download JS bundle. Did you forget to start development server or connect your device?

I try to ReactWindows/react-native folder command line  run "npm start or react-native start", no work. 

Please tell me how to start development server?

**Comment by ebragge** [comment]
node local-cli/cli.js start

**Comment by rozele** [comment]
Hey @Kennytian, we haven't released anything on NPM yet (thus running npm install react-native would drop a release of React Native into your node_modules folder that does not have any of the Windows implementation). 

So the best way to start the local CLI service is as @ebragge described, which is documented in the instructions for the Playground project: https://github.com/ReactWindows/react-native/tree/WindowsStore/ReactWindows/Playground/README.md

**Comment by Kennytian** [comment]
@ebragge  @rozele  Thanks,  ReactWindows is work!  :+1:
