### ISSUE TITLE
Add support for text 'backgroundColor' style

### ISSUE THREAD

**Issue by rozele** [ReactWindows/react-native#378]
This is easily achievable with a backing view, so very low priority, but many users will likely expect this to work in the RCTText view manager.

**Comment by mkdotcom** [comment]
backgroundColor in <Text> doesn't seems to work with "react-native-windows": "0.35.0" (I don't know if it did work before)

**Comment by rozele** [comment]
@mkdotcom this hasn't worked before.  The current native text view we're using doesn't support background color, so the only current option is to put a view with a background color behind the text.
