### ISSUE TITLE
Element Inspector flag is incorrect

### ISSUE THREAD

**Issue by mpodwysocki** [ReactWindows/react-native#408]
If you have the element inspector running and then quit the app, and launch the app again, the element inspector is no longer running. If you want the element inspector to run again, you must click the dev menu, and then it incorrectly shows "Hide Element Inspector".

**Comment by rozele** [comment]
I think the solution here is probably to disable using local settings for the Element Inspector.  The default value on app start for IsElementInspectorEnabled should always be false, regardless of the state when the app was last terminated.
________________________________

**Comment by FLGMwt** [comment]
Looks like just turning `IsElementInspectorEnabled` into an vanilla automatic does the job. Is there a need for something more robust?

Also, is it only `ElementInspector` that we want to take out of LocalSettings? Looks like Android keeps track of FPS counter, Live Reload, and Hot Reload (and actually has the same Element Inspector bug that Windows has :p). I'm for keeping parity with them, but I thought I'd ask for completeness.
