### ISSUE TITLE
VS Code Support for UWP development

### ISSUE THREAD

**Issue by sasivarnan** [ReactWindows/react-native#409]
Thanks for adding UWP support to React Native.
In [windows readme](https://github.com/ReactWindows/react-native/blob/ReactWindows/ReactWindows/Readme.md), it is mentioned that Visual Studio 2015 is needed for building and running the app.

Can we get command line tools for it and/or support for VS Code. 

Thanks in advance.

**Comment by rozele** [comment]
Hi @sasivarnan! We're actively working on CLI support (#3 and #4), and we're also working with the team that created [React Native Extension](https://github.com/Microsoft/vscode-react-native) to get it working for Windows.

However, similar to how Xcode is required for React Native iOS builds, we have a build dependency on Visual Studio 2015 and the Universal Windows SDK.  [Visual Studio 2015 Community](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) is available for free for individual developers, open source projects, academic research, education, and small professional teams.

**Comment by sasivarnan** [comment]
@rozele Thanks for the reply.
Will the dependency on Visual Studio 2015 removed after the implementation of CLI and/or the extension?

Similar to android, shall we install Windows 10 UWP SDK and use our own IDE to build applications?
